network:
  ethernets:
    enp1s0:
      dhcp4: false
      dhcp6: false
      addresses:
      - 192.168.0.25/24
      routes:
      - to: default
        via: 192.168.69.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
  version: 2
